# Numpy package

In [1]:
#Numpy!!

"""
Numpy is Numerical Python:
 - a powerful N-dimensional array object
 - sophisticated (broadcasting) functions
 - tools for integrating C/C++ and Fortran code
 - useful linear algebra, Fourier transform, and random number capabilities
"""

import numpy as np #Y ou will typically see numpy imported as np

print(dir(np)) # There is a lot here



['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'PackageLoader', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_distributor_init', '_globals', '_import_tools', '_mat', '_mklinit', '_numpy_tester', 'abs'

## Numpy arrays - primary data format
Numpy arrays are very similar to python's list, but only allow one type of object (int, str, float, etc)

We can define a numpy array with:
`np.array([data])`

In [2]:
# Numpy Array

import numpy as np
print("**********\nArrays vs Lists:")
# Numpy arrays are very similar to our standard list in form, but have a lot more functionality
arr = np.array([1, 2, 3]) # For a numpy array, we pass a list of elements to the np.array() method
print(arr)

# But numpy values are homogeneous, menaing it can only store one type of object
ints = np.array([1,2,3])
floats = np.array([1.1, 2.2, 3])
strs = np.array([1,2,3, 'hello'])
objs = np.array([1,2,3, 'hello', {}])
print(ints.dtype)
print(floats.dtype)
print(strs.dtype)
print(objs.dtype)
# Reason for this is that numpy is all about operations on vectors/matrices
# In other words, Numpy is about linear algebra

**********
Arrays vs Lists:
[1 2 3]
int64
float64
<U21
object


## Multi-Dimensional Arrays/Matrices
One of the areas in which Numpy provides benefit over a python list is in the creation of multidimensional matrices.

Each set of **[ ]**s indicates a new dimension to our data.

In [3]:
# Multidimensional Array Objects

import numpy as np
print("**********\nMultidimensional Arrays:")
# Comma seperated lists within lists create new dimensions of the data
arr = np.array([[1, 2, 3],
            [4, 5, 6]])
print(arr)
# It is multidimensional meaning you need multiple coordinates to access a point
print("\n Value in first row, first col = {}".format(arr[0][0]))

print("\n**********\n3d Array:")
# We add an index for each dimension created
arr3d = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                  
                [[10,11,12],
                [13,14,15],
                [16,17,18]]])
print(arr3d)
print("\nValue in 2nd set, first row, third col = {}".format(arr3d[1][0][2]))
# Actually not really different than if we made a multidimensional list, but more common in Numpy


**********
Multidimensional Arrays:
[[1 2 3]
 [4 5 6]]

 Value in first row, first col = 1

**********
3d Array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]

Value in 2nd set, first row, third col = 12


### Matrix Shape
To easily see the dimensions of the matrices that we create we can call **shape**

`arr.shape()`

In [4]:
# Viewing the shape of our array

print(arr3d.shape) # The shape attribute of an array tells us its dimensions

# The shape tells us, in descending order, the number of elements at each dimension
print(f'arr3d has {arr3d.shape[0]}, or {len(arr3d)}, elements in the first dimension')

# np_array.shape is a great way for understanding the format of the data you are working with

(2, 3, 3)
arr3d has 2, or 2, elements in the first dimension


## Reshaping our Matrices

It is very commmon that we may need to reshape our data - change it's dimensions.

We can easily do this with `arr.shape = (new_shape)` or `new_arr = arr.reshape(new_shape)`. The major difference between the two is that `arr.shape` will alter the current array, while `arr.reshape()` generates a new array.

In [7]:
# Reshaping Arrays
import numpy as np

print("**********\nMultidimensional Arrays:")
print("2D:")
arr = np.array([1,2,3,4,5,6,7,8,9])
arr2 = arr.reshape(3,3)
arr.shape = (3,3) # This lets us redefine the shape of the data
print(f'Array 1:\n{arr}')
print(f'Array 1:\n{arr2}')

print("\n1D:")
arr.shape = (9) #Can creat a 1D array
print(arr)

print("\n3D:")
arr = np.array([list(range(27))])
arr.shape = (3,3,3) #Think a (rubik's??) cube of data
print(arr)

try:
    arr.shape = (2) #Issue if dimensions don't match up with array
except Exception as err:
    print(f'\nError:\n{err}')

# We can pass in undefined size attributes though
arr.shape = (3, -1)
print("\n 2D Generalized:")
print(arr)



**********
Multidimensional Arrays:
2D:
Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

1D:
[1 2 3 4 5 6 7 8 9]

3D:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Error:
cannot reshape array of size 27 into shape (2,)

 2D Generalized:
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]


## In class work

In [47]:
#IN CLASS WORK

"""Numpy array indexing works exactly like all indexing/splicing in python
Take some time and play around with splicing multidimensional arrays
 - Can you get it to print out ever 3rd row of a (50, 2) array?"""

arr = np.arange(100) # Creates an array based on range function - 0-100 in this case
arr = arr.reshape(50, 2) # We reshape it to our (50, 2) setup
for i in range(50):
    if i %3 == 0:
        print(arr[i])
print(arr[::3])


[0 1]
[6 7]
[12 13]
[18 19]
[24 25]
[30 31]
[36 37]
[42 43]
[48 49]
[54 55]
[60 61]
[66 67]
[72 73]
[78 79]
[84 85]
[90 91]
[96 97]
[[ 0  1]
 [ 6  7]
 [12 13]
 [18 19]
 [24 25]
 [30 31]
 [36 37]
 [42 43]
 [48 49]
 [54 55]
 [60 61]
 [66 67]
 [72 73]
 [78 79]
 [84 85]
 [90 91]
 [96 97]]


In [48]:
#1D 
oneD = np.arange(24)
print(oneD )
print('\n')
twoD = oneD.reshape(2,12)
print(twoD )
print('\n')
threeD = oneD.reshape(2,2,6)
print(threeD )
print('\n')
fourD = oneD.reshape(2,2,2,3)
print(fourD)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]]


[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]]


## Array Slice
We can take a slice of any array with simple indexing, just like a list.

`arr_slice = arr[i:j]`

In [25]:
# Altering a Slice

import numpy as np
print("**********\nAltering a Slice:")
arr = np.arange(10)
arr_slice = arr[3:6]
print(arr_slice)
arr_slice[0] = 100 # This updates the first element in arr_slice
print(arr_slice)
# What do you think this operation changes in arr?
print(arr)

# Remember a numpy variable points to a point in memory.
# Thus a slice simply points to a specific portion of another array


**********
Altering a Slice:
[3 4 5]
[100   4   5]
[  0   1   2 100   4   5   6   7   8   9]


In [28]:
a = np.array([1,2,3])
b= a 
c= a.copy()

c[0] = 99

print(a)
print(b)
print(c)

[1 2 3]
[1 2 3]
[99  2  3]


## Creating Arrays
There are a number of ways to create arrays. These are just a couple shortcuts to create arrays of information.

In [29]:
# Creating Arrays

import numpy as np
print("\n**********\nUsing Nested Lists:")
data = [[1, 24, 54],[124, 54, 3]] # Data for 2d array
arr = np.array(data)
print(arr)


print("\n**********\nUsing Arange:")
arr = np.arange(10) # arange works a lot like list splicing (begin, end, jump)
print(arr)

print("\n**********\nUsing np.linspace:")
x, y, z = 0, 10, 5
arr = np.linspace(x, y, z) # Creats an array of z equally spaced points between x and y
print(arr)



**********
Using Nested Lists:
[[  1  24  54]
 [124  54   3]]

**********
Using Arange:
[0 1 2 3 4 5 6 7 8 9]

**********
Using np.linspace:
[ 0.   2.5  5.   7.5 10. ]


### In class work

In [45]:
#Problem 1
"""Create an 3-D array comprised of the first 27 even numbers"""
q1_array = np.linspace(2,54,27)

q1_array.shape=(3,3,3)
print(q1_array)


#Problem 2
"""Create a function 'create_int_linspace' that takes in three integers (start, stop, and pts).
The function should return np.linspace(start, stop, pts), but the result should only contain ints.
If the given parameters won't return an array of integers, increase the stop parameter to the first value
that will generate the required results

Ex. np.linspace(5, 100,3) would normally return array([   5. ,   52.5,  100. ])
 instead we would want to increase 100 to 101 to get ([   5. ,   53,  101. ])"""

import math

def create_int_linspace(start, stop, pts):
    new_arr = np.linspace(start,stop,pts)
    for i in range(len(new_arr)):
        new_arr[i] = math.ceil(new_arr[i])
    return new_arr
test_array = create_int_linspace(5,100,3)
print(test_array)
    

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]]

 [[20. 22. 24.]
  [26. 28. 30.]
  [32. 34. 36.]]

 [[38. 40. 42.]
  [44. 46. 48.]
  [50. 52. 54.]]]
[  5.  53. 100.]


## Empty Arrays
Sometimes we may want to create an emtpy array with a given structure to load information in later.

In [46]:
# Creating 'Empty Arrays

import numpy as np
print("**********\nCreating Array of zeroes:")
# We don't always know what will be filling our arrays, or simply need a place holder
z1 = np.zeros(10) # Create an array of x zeroes
print(z1)

print("\n**********\nCreating Array of x,y,... Dimensions:")
# We can also pass in a tuple for more dimensions
z2 = np.zeros((5, 3))
print(z2)

print("\n**********\nFilling with Ones and Random:")
ones = np.ones(5)
print(ones)
twos = np.ones(5)*2
print(twos)
# We can also fill the array with random values
# There are a number of random generators (from distributions, ranges, etc)
rand = np.random.rand(3,3,3)
print("\nRandom results:\n{}".format(rand))


**********
Creating Array of zeroes:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

**********
Creating Array of x,y,... Dimensions:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

**********
Filling with Ones and Random:
[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]

Random results:
[[[0.97066549 0.88301584 0.37797674]
  [0.26214453 0.82122366 0.519255  ]
  [0.9162835  0.40364323 0.90307602]]

 [[0.25714661 0.90587864 0.41668588]
  [0.35480359 0.90122688 0.1332152 ]
  [0.14555708 0.38650347 0.50329309]]

 [[0.17463299 0.91855977 0.48076387]
  [0.4102437  0.9385907  0.31298526]
  [0.57052562 0.27457101 0.56094977]]]


## Random Arrays
In addition to empty arrays, very commonly we will want to create arrays based on given probability distributions.

In [49]:
# Generating Random Arrays:

import numpy as np
import numpy.random as rand

print("**********\nGenerating Data:")
# There are a ton of ways to generate data in numpy, but here are some examples (more at - https://docs.scipy.org/doc/numpy/reference/routines.random.html)

print("**********\nnumpy.random.rand():")
arr1 = rand.rand(3,3) # Random #'s in given shape, values [0,1)
print(arr1)

print("**********\nnumpy.random.randn():")
arr1 = rand.randn(3,3) # Same as rand(), but follows the standard normal - mean:0, SD:1
print(arr1)

print("**********\nnumpy.random.randn():")
arr1 = rand.normal(loc = 5, scale = 2, size = (4,5)) # Normal distribution - mean(loc):5, SD(scale):2
print(arr1)


print("**********\nnumpy.random.randint():")
arr1 = rand.randint(0, 10, size = (4,5)) # Normal distribution - mean(loc):5, SD(scale):2
print(arr1)


# Take some time to generate a random array...


**********
Generating Data:
**********
numpy.random.rand():
[[0.09048328 0.05806973 0.09516237]
 [0.84482755 0.81124861 0.39051952]
 [0.74580625 0.86288254 0.37306352]]
**********
numpy.random.randn():
[[ 2.39359063  0.66308823 -1.3985827 ]
 [-1.01864884  1.54432627 -0.11853921]
 [-1.21789454 -1.04367488  1.71286397]]
**********
numpy.random.randn():
[[4.00251772 7.10568292 8.67295702 5.93722233 3.78044957]
 [2.76749789 6.22212304 2.8398664  5.17081457 3.65501592]
 [4.98121212 3.19388865 3.44255854 4.4637659  6.53939344]
 [4.94289005 3.74605743 3.61790172 5.37144692 2.45881271]]
**********
numpy.random.randint():
[[5 7 1 2 8]
 [9 4 2 8 6]
 [4 4 4 6 6]
 [5 3 7 8 0]]


### Why would we want empyt or randomly generated matrices?

## Numpy Types

In [50]:
# NumPY's Types and Shapes

import numpy as np

print("\n**********\nHow Does Numpy Deal With Different Types:")
# Sadly this is a bit complicated
arr1 = np.random.rand(3)
arr2 = arr1
arr2[0] = 4
# Numpy doesn't copy arrays when initializing new arrays
print("\nPrinting arr1 and arr2:")
print(arr1)
print(arr2)

# But it goes farther than that
arr2 = arr1.astype(int) #astype is used to change the element types
print("\nPrinting arr1 and arr2:")
print(arr1)
print(arr2)

# While these look like completely different arrays....
print("\nThe indexed values are stored in the same memory address???")
print(hex(id(arr1[1]))) #id allows us to see where a variable is stored in memory
print(hex(id(arr2[1])))



**********
How Does Numpy Deal With Different Types:

Printing arr1 and arr2:
[4.         0.17339618 0.31061576]
[4.         0.17339618 0.31061576]

Printing arr1 and arr2:
[4.         0.17339618 0.31061576]
[4 0 0]

The indexed values are stored in the same memory address???
0x10dbebae0
0x10dbebae0


**What is effectively going on is that Numpy simply provides different perspectives for the same data in "raw" memory. This approach means Numpy can define a variety of dtypes, slicing, etc. that simply applied to the same data in memory. This is what enables us to reshape and split and splice arrays with ease. But this means that we need to explicitly copy an array if we want to maniuplate the data.**

## Copying Arrays

In [51]:
# Copying arrays

arr1 = np.random.randint(3, size=(5,))
arr2 = arr1.copy()

arr2[0] = 100

print(f'Array 1: {arr1}')
print(f'Array 2: {arr2}')

"""Notice that it keeps the general structure, but the values now point to different
points in memory, as they don't update each other."""

Array 1: [2 0 0 0 0]
Array 2: [100   0   0   0   0]


"Notice that it keeps the general structure, but the values now point to different\npoints in memory, as they don't update each other."